apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentication-service-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication-service-db
  template:
    metadata:
      labels:
        app: authentication-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: authentication_service_db # DÜZELTİLDİ: properties ile uyumlu
            - name: POSTGRES_USER
              value: user     # DÜZELTİLDİ: properties ile uyumlu
            - name: POSTGRES_PASSWORD
              value: password # 
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: authentication-service-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service-db
spec:
  selector:
    app: authentication-service-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432