spring:
  application:
    name: content-management-service
  
  cloud:
    compatibility-verifier:
      enabled: false

# Server Configuration
server:
  port: ${SERVER_PORT:9200}
  error:
    include-message: always
    include-binding-errors: always

# Eureka Configuration
# eureka:
#   client:
#     service-url:
#       defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
#     register-with-eureka: true
#     fetch-registry: true
#   instance:
#     prefer-ip-address: true
#     lease-renewal-interval-in-seconds: 30
#     lease-expiration-duration-in-seconds: 90

# gRPC Server Configuration
grpc:
  server:
    port: ${GRPC_SERVER_PORT:9290}


