apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-db-pvc # Bu disk alanının adı
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi # Test için 500MB yeterli
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service-db
  template:
    metadata:
      labels:
        app: user-service-db
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env: # Docker Compose'daki değerlerin aynısı
            - name: POSTGRES_DB
              value: user_service_db
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
            - name: POSTGRES_INITDB_ARGS
              value: "-E UTF8"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          persistentVolumeClaim:
            claimName: user-service-db-pvc # Yukarıda talep ettiğimiz diski kullan
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-db # User Service bu isme bağlanacak (DB_HOST)
spec:
  selector:
    app: user-service-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432