spring:
  application:
    name: authentication
  
  cloud:
    compatibility-verifier:
      enabled: false

# Server Configuration
server:
  port: ${SERVER_PORT:8000}
  error:
    include-message: always
    include-binding-errors: always

# Eureka Configuration
# eureka:
#   client:
#     service-url:
#       defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka}
#     register-with-eureka: true
#     fetch-registry: true
#   instance:
#     prefer-ip-address: true
#     lease-renewal-interval-in-seconds: 30
#     lease-expiration-duration-in-seconds: 90

# gRPC Client Configuration
# dns:/// kullanarak dinamik DNS çözümlemesi sağlanır
# Bu sayede Docker Swarm'da servis restart olduğunda otomatik olarak yeni adresi bulur
grpc:
  client:
    user-service:
      address: dns:///${USER_SERVICE_GRPC_HOST:user-service}:${USER_SERVICE_GRPC_PORT:9090}
      negotiation-type: plaintext
      enable-keep-alive: true
      keep-alive-time: 30s
      keep-alive-timeout: 10s
